### ISSUE TITLE
Correct extension

### ISSUE THREAD

**Issue by francisdb** [EngineersNeedArt/VPX_EM_Resources#1]
The correct extension for VBScript is `.vbs` instead of `.bas`

**Comment by francisdb** [comment]
Some of us should work together on this kind of repository.

**Comment by EngineersNeedArt** [comment]
Hi, Francis — 

You're obviously knowledgeable about VPX. Thanks for reaching out as I have only been dabbling in it, trying to figure it out.

I'll begin today to go through some of your feedback and see the degree to which it helps to update the blog series I created this repo for.

My audience are not just people new to VPX scripting as I am (and as you are aware, I am also new to Visual Basic), but I also don't expect my audience to have programming skills since that seems to be the kind of VPX enthusiasts I have met.

I think there are a number of people for whom the script to a VPX table is a scary "black box" and I hope to demystify that. In part, or because of, my own naiveté having only approached both VPX and Visual Basic 6 months ago.

I can monitor this thread if you would like to communicate this way.

John Calhoun—

EDIT: renaming the files to have the correct extension did require me to update my blog so that I have the correct link. Unfortunately (due to my blog) there is a bit of fragility at least to the file names that I have to be careful about.

https://engineersneedart.com/blog/cutpaste/cutpaste.html

**Comment by francisdb** [comment]
You're doing a great job coming up with these blog posts! VBScript is new (or very old) for most of us :-)
